config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'contact#contact'
  get 'landing', to: 'landing#projectlanding'
  get 'about_me', to: 'pages#about_me'
  get 'home_test', to: 'pages#home_test'
  root to: 'pages#home'

  resources :contact, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "ashanti.richardson@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contact
    @contact = Contact.new(params[:contact])
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        # re-initialize Contact object for cleared form
        @contact = Contact.new
        format.html { render 'contact'}
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'contact' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about_me
  end

  def contact
  end

  def home_test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_contact_form.html.erb
<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
  <div class="container flex">

    <div class="col-md-6 col-lg-6 contact">
      <h2 class="mt-3 mb-5">Contact me!</h2>
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :email %></br>
        <%= f.text_field :email, required: true, class: "contact-form-text-area" %></br>

        <%= f.label :message %></br>
        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area",
                          placeholder: "Send me a message"%></br>

      <div class= "hidden">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
      </div>

      <%= f.submit 'Send Message', class: 'btn btn-primary' %>
    </div>
    <% end %>


    <div class="contact_info col-md-6 contact mt-3 hidden ">
      <h2>If you prefer to contact me in your own format:</h2>
      <p>ashanti.richardson@gmail.com</p>
      <p>0031636499515</p>
    </div>



  </div>


    <div class="col-md-6" id="flash-message">
      <%= render 'flash' %>
    </div>

app/views/contact/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/contact/contact.html.erb
<%= render 'shared/navbar' %>

<div class="container">
  <!-- <h2 class="contact">Contact me!</h2> -->
</div>
  <div id="contact">
    <%= render 'contact_form' %>
  </div>


<footer class="foot bottom">
  <p>+31636499515</p>
  <p>ashanti.richardson@gmail.com</p>
  <div class="icon">
    <a href="https://www.linkedin.com/in/ashanti-richardson-71b4a6b1/" class="icon"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="icon">
    <a href="https://github.com/acrichardson" class="icon"><i class="fab fa-github"></i></a>
  </div>
  <div class="icon">
    <a href="https://www.facebook.com/ashanti.richardson" class="icon"><i class="fab fa-facebook-f"></i></a>
  </div>
</footer>

app/views/contact/create.js.erb
// Test for ajax success
console.log("This is the create.js.erb file");
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/landing/projectlanding.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>My tempoarily broken landing page</title>
  <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">
  <link href="https://fonts.googleapis.com/css?family=Domine:400,700|Roboto:400,700,900&display=swap" rel="stylesheet">
  <!-- We need this line below for responsiveness! -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="css/style.css">
</head>
<body>

<%= render 'shared/navbar' %>

  <div class="banner">

    <div class="banner-card">
      <div>
      <h1>Call your audience to action!</h1>
      <p class="text_soft_banner" >Change your life and learn to code at one of our campuses</p>
      <a class="button" href="">Apply now!</a>
      </div>
    </div>
  </div>

  <!-- code a "How it works" section -->
  <div class="hiw">
    <h2 class="landing_margin">How it works</h2>

    <div class="hiw-container">
      <div class="hiw-container-card">
        <img class="img_in_container" src="../../assets/apply.svg" alt="something">

        <h3>Apply</h3>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>
      <div class="hiw-container-card">
        <img class="img_in_container" src="../../assets/learn.svg" alt="something">
        <h3>Learn to code</h3>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>
      <div class="hiw-container-card">
        <img class="img_in_container" src="../../assets/product.svg" alt="something">
        <h3>Build products</h3>
        <p>Lorem ipsum dolor sit amet.</p>
      </div>
    </div>

  </div>

  <!-- code a footer -->
  <div>
    <footer class="footer">
      <div>

      <div class="icons">
        <a href="#" class="icons"><i class="fab fa-facebook-f"></i></a>
        <a href="#" class="icons"><i class="fab fa-instagram"></i></a>
        <a href="#" class="icons"><i class="fab fa-reddit"></i></a>
        <a href="#" class="icons"><i class="fab fa-github"></i></a>
        <a href="#" class="icons"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="footer-text">
      </div>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ashanti Richardson</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Codystar&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet"> -->
    <!-- <link href="https://fonts.googleapis.com/css2?family=Oswald&family=Poppins&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text&family=Montserrat&family=Oswald&family=Poppins&family=Roboto&display=swap" rel="stylesheet">

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
<div>
    <%= yield %>
</div>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about_me.html.erb
<%= render 'shared/navbar' %>


<div class="container m-0 p-0">
  <div class="row">
    <div class="col-sm-12 col-lg-5 mb-3 p-0 mr-5 pad about_text">
      <div class="m-3 mt-5">

        <h1 class="montserrat mb-3 ">About me</h1>
        <div class="montserrat">

          <p>I am a junior web developer based in Amsterdam.</p>
          <p>I enjoy problem solving and creating helpful and enjoyable things from scratch.</p>
          <p>My coding adventure started about a year ago. From that time I have immersed myself in code as much as possible. I have finished the 9 week Le Wagon fullstack web development course and have been coding everyday since.</p>
          <p>I'm looking for a possibility to learn more about coding. I love building reactive web applications and doing anything that can deepen my knowledge about code.</p>

          Stack:
          Ruby on Rails,
          HTML,
          JavaScript ES2015,
          CSS,
          SQL,
          React,
          Bootstrap,
          git,
          GitHub,
          Heroku
        </div>
      </div>
    </div>



    <div class="col-sm-12 col-lg-4 ml-5">
      <div class="ava">
        <!-- <div class="image"> -->

          <!-- <img src="../../assets/ashanti.png" alt=""> -->
          <%= cl_image_tag("ashanti2") %>
          <!-- </div> -->
        </div>



      </div>
    </div>
  </div>

  <div class="space">

  </div>




  <%= render 'shared/foot_home' %>














<!--

<h1 class="ml8">
  <span class="letters-container">
    <span class="letters letters-left">Hi</span>
    <span class="test">Hi!</span>
    <span class="letters bang">!</span>
  </span>
  <span class="circle circle-white"></span>
  <span class="circle circle-dark"></span>
  <span class="circle circle-container"><span class="circle circle-dark-dashed"></span></span>
</h1>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

<script>
  anime.timeline({loop: true})
  .add({
    targets: '.ml8 .circle-white',
    scale: [0, 3],
    opacity: [1, 0],
    easing: "easeInOutExpo",
    rotateZ: 360,
    duration: 1100
  }).add({
    targets: '.ml8 .circle-container',
    scale: [0, 1],
    duration: 1100,
    easing: "easeInOutExpo",
    offset: '-=1000'
  }).add({
    targets: '.ml8 .circle-dark',
    scale: [0, 1],
    duration: 1100,
    easing: "easeOutExpo",
    offset: '-=600'
  }).add({
    targets: '.ml8 .letters-left',
    scale: [0, 1],
    duration: 1200,
    offset: '-=550'
  }).add({
    targets: '.ml8 .bang',
    scale: [0, 1],
    rotateZ: [45, 15],
    duration: 1200,
    offset: '-=1000'
  }).add({
    targets: '.ml8',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1400
  });

anime({
  targets: '.ml8 .circle-dark-dashed',
  rotateZ: 360,
  duration: 8000,
  easing: "linear",
  loop: true
});
</script> -->

app/views/pages/home.html.erb
<div class="home_background">

  <%= render 'shared/navbar' %>
  <div class="container ml-0 mr-0 margintop_AR">
    <div class="row myname">
      <div class="col-8 mb-5">

        <h1 class="name_font home_text" >Ashanti Richardson</h1>
        <h3 class="home_text ml3" >Full Stack Web Developer</h3>
        <h6 class="home_text ml4">
          <span class="letters letters-3"> (junior)</span>
        </h6>
      </div>
    </div>
  </div>

  <div class="flex projects">
    <h1 class="name_font m-auto">projects</h1>
  </div>
<!-- <div class="container">
  <div class="intro">
    <p>introduction</p>
  </div>
</div> -->

<div class="container m-0 p-0 ml-3">
  <div class="row">
    <div class="col-sm-12 col-lg-6 mb-3 pad">
      <%= cl_image_tag("packed", class:"col-sm-12 img_homer mb-5 pad") %>
    </div>
    <div class="col-sm-12 col-lg-6 mb-5 pl-5">
      <h5 class="montserrat mb-3 pad">PackedRight:</h5>

      <p class="montserrat">PackedRight is an Uber inspired platform but then it focuses on parcels alone. Users can log in and make a profile. They can see if there are suitable drivers in their area and book a ride for parcels of any kind. They can follow their selected driver as they approach and chat with them to ask questions. The driver can update the status of a package with just one click. Users and drivers can give each other ratings after the ride is done.</p>
    </div>
  </div>
</div>

<div class="container m-0 p-0 ml-3">
  <div class="row">
    <div class="col-sm-12 col-lg-6 mb-3 pad">
      <%= cl_image_tag("rentart", class:"col-sm-12 img_homer mb-5 pad") %>
    </div>
    <div class="col-sm-12 col-lg-6 mb-5 pl-5">
      <h5 class="montserrat mb-3"h5>Rentart:</h5>
      <p class="montserrat">Rentart is a platform where people can rent high-end tranport vehicles. On the platform people can add a profile for themselvesa as a user or add their own items that they would like to rent out. The categories available are 'helicopters', 'cars', 'planes' and 'other'. Users can leave reviews and give stars for their experiences. They can manage their reservations and message each other.  </p>
    </div>
  </div>
</div>

<div class="container m-0 p-0 ml-3">
  <div class="row">
    <div class="col-sm-12 col-lg-6 mb-3 pad">
      <%= cl_image_tag("cocktails_app", class:"col-sm-12 img_homer mb-5 pad") %>
    </div>
    <div class="col-sm-12 col-lg-6 mb-5 pl-5">
     <h5 class="montserrat mb-3"h5>Cocktails:</h5>
     <p class="montserrat">Molo Cocktails is a site where you browse for your favorite classic cocktails but also add your own creations with pictures. </p>

   </div>
 </div>
</div>

<div class="container m-0 p-0 ml-3">
  <div class="row">
    <div class="col-sm-12 col-lg-6 mb-3 pad">
      <%= cl_image_tag("landing_page", class:"col-sm-12 img_homer mb-5 pad") %>
    </div>
    <div class="col-sm-12 col-lg-6 mb-5 pl-5">
      <h5 class="montserrat mb-3"h5>Landing Page:</h5>
      <p class="montserrat">A basic landing page</p>
    </div>
  </div>
</div>



<div class="">

</div>
</div>

<div class="">
  <%= render 'shared/foot_home' %>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

<script type="text/javascript">
  var textWrapper = document.querySelector('.ml3');
  textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

  anime.timeline({loop: true})
  .add({
    targets: '.ml3 .letter',
    opacity: [0,1],
    easing: "easeInOutQuad",
    duration: 2250,
    delay: (el, i) => 150 * (i+1)
  }).add({
    targets: '.ml3',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1000
  });

  //////////////////////
  var ml4 = {};
  ml4.opacityIn = [0,1];
  ml4.scaleIn = [0.2, 1];
  ml4.scaleOut = 3;
  ml4.durationIn = 800;
  ml4.durationOut = 6000;
  ml4.delay = 500;

  anime.timeline({loop: true})
  .add({
    targets: '.ml4 .letters-1',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-1',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4 .letters-2',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-2',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4 .letters-3',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-3',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4',
    opacity: 0,
    duration: 500,
    delay: 500
  });

</script>

app/views/pages/home_test.html.erb
<div class="home_background">

  <%= render 'shared/navbar' %>
  <div class="container margintop_AR">
    <div class="row myname">
      <div class="col-8 mb-5">

        <h1 class="name_font home_text" >Ashanti Richardson</h1>
        <h3 class="home_text ml3" >Full Stack Web Developer</h3>
        <h6 class="home_text ml4">
          <span class="letters letters-3"> (junior)</span>
        </h6>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-lg-6">
        <%= cl_image_tag("packed", class:"img_homer") %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <p class="montserrat">PackedRight is an Uber inspired platform but then it focusses on parcels alone. Users can log in and make a profile. They can see if there are suitable drivers in their area and book a ride for parcels of any kind. They can follow their selected driver as they approach and chat with them to ask questions. The driver can update the status of a package with just one click. Users and drivers can give each other ratings after the ride is done.</p>
      </div>
      <div class="col-sm">
        One of three columns
      </div>
    </div>
  </div>

















<!-- <div class="container">
  <div class="intro">
    <p>introduction</p>
  </div>
</div> -->
<div class="flex projects">
  <h1 class="name_font m-auto">projects</h1>
</div>

<div class="">

  <ul class="p-0 m-4">
    <div class="flex m-3">
      <li class="">
        <!-- <img class="half img_homet" src="../../assets/packed.png" alt="something"> -->
        <%= cl_image_tag("packed", class:"half img_homet") %>
      </li>
      <div class="description half mt-1">
        <h5 class="montserrat mb-3">PackedRight:</h5>
        <p class="montserrat">PackedRight is an Uber inspired platform but then it focusses on parcels alone. Users can log in and make a profile. They can see if there are suitable drivers in their area and book a ride for parcels of any kind. They can follow their selected driver as they approach and chat with them to ask questions. The driver can update the status of a package with just one click. Users and drivers can give each other ratings after the ride is done.</p>
      </div>
    </div>

    <div class="flex m-3">
      <div class="description half mt-1">
        <h5 class="montserrat mb-3"h5>Rentart:</h5>
        <p class="montserrat">Rentart is a platform where people can rent high-end tranport vehicles. On the platform people can add a profile for themselvesa as a user or add their own items that they would like to rent out. The categories available are 'helicopters', 'cars', 'planes' and 'other'. Users can leave reviews and give stars for their experiences. They can manage their reservations and message each other.  </p>
      </div>
      <li class="">
        <!-- <img class="half img_homet" src="../../assets/rentart.png" alt="something"> -->
        <%= cl_image_tag("rentart", class:"half img_homet") %>
      </li>
    </div>

    <div class="flex m-3">
      <li class="">
        <!-- <img class="half img_homet" src="../../assets/cocktailsinval.png" alt="something"> -->
        <%= cl_image_tag("cocktails_app", class:"half img_homet") %>
      </li>
      <div class="description half mt-1">
        <h5 class="montserrat mb-3"h5>Cocktails:</h5>
        <p class="montserrat">Molo Cocktails is a site where you brows for your favorite classic cocktails but also add your own creations with pictures. </p>
      </div>
    </div>

    <div class="flex m-3">
      <div class="description half mt-1">
        <h5 class="montserrat mb-3"h5>Landing Page:</h5>
        <p class="montserrat">A basic landing page</p>
      </div>
      <li class="">
        <!-- <img class="half img_homet" src="../../assets/landing page.png" alt="something"> -->
        <%= cl_image_tag("landing_page", class:"half img_homet") %>
      </li>
    </div>
  </ul>
</div>
</div>

<div class="">
  <%= render 'shared/foot_home' %>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>

<script type="text/javascript">
  var textWrapper = document.querySelector('.ml3');
  textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

  anime.timeline({loop: true})
  .add({
    targets: '.ml3 .letter',
    opacity: [0,1],
    easing: "easeInOutQuad",
    duration: 2250,
    delay: (el, i) => 150 * (i+1)
  }).add({
    targets: '.ml3',
    opacity: 0,
    duration: 1000,
    easing: "easeOutExpo",
    delay: 1000
  });

  //////////////////////
  var ml4 = {};
  ml4.opacityIn = [0,1];
  ml4.scaleIn = [0.2, 1];
  ml4.scaleOut = 3;
  ml4.durationIn = 800;
  ml4.durationOut = 6000;
  ml4.delay = 500;

  anime.timeline({loop: true})
  .add({
    targets: '.ml4 .letters-1',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-1',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4 .letters-2',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-2',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4 .letters-3',
    opacity: ml4.opacityIn,
    scale: ml4.scaleIn,
    duration: ml4.durationIn
  }).add({
    targets: '.ml4 .letters-3',
    opacity: 0,
    scale: ml4.scaleOut,
    duration: ml4.durationOut,
    easing: "easeInExpo",
    delay: ml4.delay
  }).add({
    targets: '.ml4',
    opacity: 0,
    duration: 500,
    delay: 500
  });

</script>

app/views/shared/_foot.html.erb
  <div>
    <footer class="foot bottom">
      <div class="icon">
        <a href="https://www.facebook.com/ashanti.richardson" class="icon"><i class="fab fa-facebook-f"></i></a>
      </div>
      <div class="icon">
        <a href="#" class="icon"><i class="fab fa-instagram"></i></a>
      </div>
      <!-- <div class=""> -->
        <!-- <%= mail_to "ashanti.richardson@gmail.com", "ashanti.richardson@gmail.com" %> -->
        <!-- <p>ashanti.richardson@gmail.com</p> -->
      <!-- </div> -->
      <div class="icon">
        <a href="https://github.com/acrichardson" class="icon"><i class="fab fa-github"></i></a>
      </div>
      <div class="icon">
        <a href="https://www.linkedin.com/in/ashanti-richardson-71b4a6b1/" class="icon"><i class="fab fa-linkedin"></i></a>
      </div>
    </footer>
  </div>

app/views/shared/_foot_home.html.erb
  <div>
    <footer class="foot">
      <div class="icon">
        <a href="https://www.facebook.com/ashanti.richardson" class="icon" target="_blank"><i class="fab fa-facebook-f"></i></a>
      </div>
      <div class="icon">
        <a href="#" class="icon" target="_blank"><i class="fab fa-instagram"></i></a>
      </div>
      <!-- <div class=""> -->
        <!-- <%= mail_to "ashanti.richardson@gmail.com", "ashanti.richardson@gmail.com" %> -->
        <!-- <p>ashanti.richardson@gmail.com</p> -->
      <!-- </div> -->
      <div class="icon">
        <a href="https://github.com/acrichardson" class="icon" target="_blank"><i class="fab fa-github"></i></a>
      </div>
      <div class="icon">
        <a href="https://www.linkedin.com/in/ashanti-richardson-71b4a6b1/" class="icon" target="_blank"><i class="fab fa-linkedin"></i></a>
      </div>
    </footer>
  </div>

app/views/shared/_navbar.html.erb
<!-- <div class="dropdown dropdown-custom alwaysontop">
  <button class="btn btn-secondary dropdown-toggle dropmenu menu" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
    <button class="dropdown-item" type="button">
    </button>
    <button class="dropdown-item" type="button"><%= link_to "Home",  root_path  %></button>

    </div>
  </div>
 -->
<div class="navbar-expand-sm navbar-light navbar-lewagon">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="nav-spread navbar-nav mr-auto">
      <div class="nav-item active navbar-nav">
        <%= link_to "Home", "/", class: "nav-link" %>
      </div>
      <div class="nav-item dropdown nav-link" >
        <p class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Projects</p>
        <div class="dropdown-menu dropdown-menu-right nav-item active" aria-labelledby="navbarDropdown">
          <%= link_to "React Chatbot (work in progress) ", 'https://arcane-crag-89252.herokuapp.com/', class: "dropdown-item", target: "_blank" %>
          <%= link_to "PackedRight", 'http://www.packedright.live', class: "dropdown-item", target: "_blank" %>
          <%= link_to "RentArt", "https://rentart2020.herokuapp.com", class: "dropdown-item", target: "_blank" %>
          <% link_to "Cocktails App", 'http://www.packedright.live', class: "dropdown-item", target: "_blank" %>
          <%= link_to "Landing page", landing_path, class: "dropdown-item", target: "_blank" %>
        </div>
      </div>
<!--       <div class="nav-item">
        <%= link_to "Projects", "/products/new", class: "nav-link" %>
      </div> -->
      <div class="nav-item">
        <%= link_to "Github", "https://github.com/acrichardson", class: "nav-link", target: "_blank" %>
      </div>
      <div class="nav-item">
        <%= link_to "About Me", about_me_path, class: "nav-link" %>
      </div>
      <div class="nav-item">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </div>
    </div>
  </div>
</div>

        <!-- <div class="dropdown-menu dropdown-menu-right nav-item active" aria-labelledby="navbarDropdown">
          <%= link_to "PackedRight", url: 'https//:www.packedright.live', class: "dropdown-item" %>
        </div>
        <div class="dropdown-menu dropdown-menu-right nav-item active" aria-labelledby="navbarDropdown">
          <%= link_to "RentArt", url: 'https//:www.packedright.live', class: "dropdown-item" %>
        </div>
        <div class="dropdown-menu dropdown-menu-right nav-item active" aria-labelledby="navbarDropdown">
          <%= link_to "Cocktails App", url: 'https//:www.packedright.live', class: "dropdown-item" %>
        </div>
        <div class="dropdown-menu dropdown-menu-right nav-item active" aria-labelledby="navbarDropdown">
          <%= link_to "Landing page", url: 'https//:www.packedright.live', class: "dropdown-item" %>
        </div> -->